AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - config/environments/*
    - bin/**/*
    - db/seeds.rb
    - db/**/*
    - deploy/**/*
    - vendor/**/*
    - lib/tasks/dev/**/*
    - node_modules/**/*
    - config/initializers/devise.rb

Rails:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 220

Metrics/AbcSize:
  Max: 35

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# allow multiline `expect { ... }.to do_something`
Style/BlockDelimiters:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Rails/SkipsModelValidations:
  Exclude:
    - "spec/**/*"
